/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissenRouteImport } from './routes/wissen'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as StromGasRouteImport } from './routes/strom-gas'
import { Route as StromRouteImport } from './routes/strom'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as MitarbeiterRouteImport } from './routes/mitarbeiter'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GewerbestromRouteImport } from './routes/gewerbestrom'
import { Route as GewerbegasRouteImport } from './routes/gewerbegas'
import { Route as GasRouteImport } from './routes/gas'
import { Route as FreundeWerbenRouteImport } from './routes/freunde-werben'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DankeRouteImport } from './routes/danke'
import { Route as AngebotRouteImport } from './routes/angebot'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MitarbeiterIndexRouteImport } from './routes/mitarbeiter.index'
import { Route as WissenSlugRouteImport } from './routes/wissen.$slug'
import { Route as MitarbeiterWiedervorlageRouteImport } from './routes/mitarbeiter.wiedervorlage'
import { Route as MitarbeiterVorlagenRouteImport } from './routes/mitarbeiter.vorlagen'
import { Route as MitarbeiterTeamRouteImport } from './routes/mitarbeiter.team'
import { Route as MitarbeiterTarifeRouteImport } from './routes/mitarbeiter.tarife'
import { Route as MitarbeiterStatistikenRouteImport } from './routes/mitarbeiter.statistiken'
import { Route as MitarbeiterReferralsRouteImport } from './routes/mitarbeiter.referrals'
import { Route as MitarbeiterRedaktionRouteImport } from './routes/mitarbeiter.redaktion'
import { Route as MitarbeiterPasswortVergessenRouteImport } from './routes/mitarbeiter.passwort-vergessen'
import { Route as MitarbeiterPasswortNeuRouteImport } from './routes/mitarbeiter.passwort-neu'
import { Route as MitarbeiterLoginRouteImport } from './routes/mitarbeiter.login'
import { Route as MitarbeiterLeadsRouteImport } from './routes/mitarbeiter.leads'
import { Route as MitarbeiterKundenRouteImport } from './routes/mitarbeiter.kunden'
import { Route as MitarbeiterEinstellungenRouteImport } from './routes/mitarbeiter.einstellungen'
import { Route as MitarbeiterDashboardRouteImport } from './routes/mitarbeiter.dashboard'
import { Route as MitarbeiterAnbieterRouteImport } from './routes/mitarbeiter.anbieter'
import { Route as ApiTeamRouteImport } from './routes/api/team'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiReferralValidateRouteImport } from './routes/api/referral-validate'
import { Route as ApiReferralRequestRouteImport } from './routes/api/referral-request'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as MitarbeiterRedaktionNeuRouteImport } from './routes/mitarbeiter.redaktion.neu'
import { Route as MitarbeiterRedaktionIdRouteImport } from './routes/mitarbeiter.redaktion.$id'
import { Route as MitarbeiterLeadsIdRouteImport } from './routes/mitarbeiter.leads.$id'
import { Route as ApiTeamIdRouteImport } from './routes/api/team.$id'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public.leads'
import { Route as ApiLeadsIdRouteImport } from './routes/api/leads.$id'
import { Route as ApiBlogArticlesRouteImport } from './routes/api/blog.articles'
import { Route as ApiReferralsIdPayRouteImport } from './routes/api/referrals.$id.pay'
import { Route as ApiLeadsIdStatusHistoryRouteImport } from './routes/api/leads.$id.status-history'
import { Route as ApiLeadsIdStatusRouteImport } from './routes/api/leads.$id.status'
import { Route as ApiLeadsIdOffersRouteImport } from './routes/api/leads.$id.offers'
import { Route as ApiLeadsIdNotesRouteImport } from './routes/api/leads.$id.notes'
import { Route as ApiLeadsIdDocumentsRouteImport } from './routes/api/leads.$id.documents'
import { Route as ApiLeadsIdCommunicationsRouteImport } from './routes/api/leads.$id.communications'
import { Route as ApiLeadsIdAssignRouteImport } from './routes/api/leads.$id.assign'
import { Route as ApiBlogArticlesSlugRouteImport } from './routes/api/blog.articles.$slug'
import { Route as ApiAdminBlogArticlesRouteImport } from './routes/api/admin.blog.articles'
import { Route as ApiLeadsIdDocumentsUploadRouteImport } from './routes/api/leads.$id.documents.upload'
import { Route as ApiAdminBlogArticlesIdRouteImport } from './routes/api/admin.blog.articles.$id'
import { Route as ApiLeadsIdDocumentsDocIdUrlRouteImport } from './routes/api/leads.$id.documents.$docId.url'

const WissenRoute = WissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const StromGasRoute = StromGasRouteImport.update({
  id: '/strom-gas',
  path: '/strom-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const StromRoute = StromRouteImport.update({
  id: '/strom',
  path: '/strom',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterRoute = MitarbeiterRouteImport.update({
  id: '/mitarbeiter',
  path: '/mitarbeiter',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GewerbestromRoute = GewerbestromRouteImport.update({
  id: '/gewerbestrom',
  path: '/gewerbestrom',
  getParentRoute: () => rootRouteImport,
} as any)
const GewerbegasRoute = GewerbegasRouteImport.update({
  id: '/gewerbegas',
  path: '/gewerbegas',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRoute = GasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const FreundeWerbenRoute = FreundeWerbenRouteImport.update({
  id: '/freunde-werben',
  path: '/freunde-werben',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DankeRoute = DankeRouteImport.update({
  id: '/danke',
  path: '/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotRoute = AngebotRouteImport.update({
  id: '/angebot',
  path: '/angebot',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterIndexRoute = MitarbeiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const WissenSlugRoute = WissenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WissenRoute,
} as any)
const MitarbeiterWiedervorlageRoute =
  MitarbeiterWiedervorlageRouteImport.update({
    id: '/wiedervorlage',
    path: '/wiedervorlage',
    getParentRoute: () => MitarbeiterRoute,
  } as any)
const MitarbeiterVorlagenRoute = MitarbeiterVorlagenRouteImport.update({
  id: '/vorlagen',
  path: '/vorlagen',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterTeamRoute = MitarbeiterTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterTarifeRoute = MitarbeiterTarifeRouteImport.update({
  id: '/tarife',
  path: '/tarife',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterStatistikenRoute = MitarbeiterStatistikenRouteImport.update({
  id: '/statistiken',
  path: '/statistiken',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterReferralsRoute = MitarbeiterReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterRedaktionRoute = MitarbeiterRedaktionRouteImport.update({
  id: '/redaktion',
  path: '/redaktion',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterPasswortVergessenRoute =
  MitarbeiterPasswortVergessenRouteImport.update({
    id: '/passwort-vergessen',
    path: '/passwort-vergessen',
    getParentRoute: () => MitarbeiterRoute,
  } as any)
const MitarbeiterPasswortNeuRoute = MitarbeiterPasswortNeuRouteImport.update({
  id: '/passwort-neu',
  path: '/passwort-neu',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterLoginRoute = MitarbeiterLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterLeadsRoute = MitarbeiterLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterKundenRoute = MitarbeiterKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterEinstellungenRoute =
  MitarbeiterEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => MitarbeiterRoute,
  } as any)
const MitarbeiterDashboardRoute = MitarbeiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterAnbieterRoute = MitarbeiterAnbieterRouteImport.update({
  id: '/anbieter',
  path: '/anbieter',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const ApiTeamRoute = ApiTeamRouteImport.update({
  id: '/api/team',
  path: '/api/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralValidateRoute = ApiReferralValidateRouteImport.update({
  id: '/api/referral-validate',
  path: '/api/referral-validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralRequestRoute = ApiReferralRequestRouteImport.update({
  id: '/api/referral-request',
  path: '/api/referral-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterRedaktionNeuRoute = MitarbeiterRedaktionNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => MitarbeiterRedaktionRoute,
} as any)
const MitarbeiterRedaktionIdRoute = MitarbeiterRedaktionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MitarbeiterRedaktionRoute,
} as any)
const MitarbeiterLeadsIdRoute = MitarbeiterLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MitarbeiterLeadsRoute,
} as any)
const ApiTeamIdRoute = ApiTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTeamRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIdRoute = ApiLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiBlogArticlesRoute = ApiBlogArticlesRouteImport.update({
  id: '/api/blog/articles',
  path: '/api/blog/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsIdPayRoute = ApiReferralsIdPayRouteImport.update({
  id: '/$id/pay',
  path: '/$id/pay',
  getParentRoute: () => ApiReferralsRoute,
} as any)
const ApiLeadsIdStatusHistoryRoute = ApiLeadsIdStatusHistoryRouteImport.update({
  id: '/status-history',
  path: '/status-history',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiLeadsIdStatusRoute = ApiLeadsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiLeadsIdOffersRoute = ApiLeadsIdOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiLeadsIdNotesRoute = ApiLeadsIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiLeadsIdDocumentsRoute = ApiLeadsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiLeadsIdCommunicationsRoute =
  ApiLeadsIdCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => ApiLeadsIdRoute,
  } as any)
const ApiLeadsIdAssignRoute = ApiLeadsIdAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => ApiLeadsIdRoute,
} as any)
const ApiBlogArticlesSlugRoute = ApiBlogArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogArticlesRoute,
} as any)
const ApiAdminBlogArticlesRoute = ApiAdminBlogArticlesRouteImport.update({
  id: '/api/admin/blog/articles',
  path: '/api/admin/blog/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIdDocumentsUploadRoute =
  ApiLeadsIdDocumentsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiLeadsIdDocumentsRoute,
  } as any)
const ApiAdminBlogArticlesIdRoute = ApiAdminBlogArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBlogArticlesRoute,
} as any)
const ApiLeadsIdDocumentsDocIdUrlRoute =
  ApiLeadsIdDocumentsDocIdUrlRouteImport.update({
    id: '/$docId/url',
    path: '/$docId/url',
    getParentRoute: () => ApiLeadsIdDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/agb': typeof AgbRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/freunde-werben': typeof FreundeWerbenRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitarbeiter': typeof MitarbeiterRouteWithChildren
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/referral-request': typeof ApiReferralRequestRoute
  '/api/referral-validate': typeof ApiReferralValidateRoute
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/team': typeof ApiTeamRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/passwort-neu': typeof MitarbeiterPasswortNeuRoute
  '/mitarbeiter/passwort-vergessen': typeof MitarbeiterPasswortVergessenRoute
  '/mitarbeiter/redaktion': typeof MitarbeiterRedaktionRouteWithChildren
  '/mitarbeiter/referrals': typeof MitarbeiterReferralsRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter/': typeof MitarbeiterIndexRoute
  '/api/blog/articles': typeof ApiBlogArticlesRouteWithChildren
  '/api/leads/$id': typeof ApiLeadsIdRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/team/$id': typeof ApiTeamIdRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
  '/mitarbeiter/redaktion/$id': typeof MitarbeiterRedaktionIdRoute
  '/mitarbeiter/redaktion/neu': typeof MitarbeiterRedaktionNeuRoute
  '/api/admin/blog/articles': typeof ApiAdminBlogArticlesRouteWithChildren
  '/api/blog/articles/$slug': typeof ApiBlogArticlesSlugRoute
  '/api/leads/$id/assign': typeof ApiLeadsIdAssignRoute
  '/api/leads/$id/communications': typeof ApiLeadsIdCommunicationsRoute
  '/api/leads/$id/documents': typeof ApiLeadsIdDocumentsRouteWithChildren
  '/api/leads/$id/notes': typeof ApiLeadsIdNotesRoute
  '/api/leads/$id/offers': typeof ApiLeadsIdOffersRoute
  '/api/leads/$id/status': typeof ApiLeadsIdStatusRoute
  '/api/leads/$id/status-history': typeof ApiLeadsIdStatusHistoryRoute
  '/api/referrals/$id/pay': typeof ApiReferralsIdPayRoute
  '/api/admin/blog/articles/$id': typeof ApiAdminBlogArticlesIdRoute
  '/api/leads/$id/documents/upload': typeof ApiLeadsIdDocumentsUploadRoute
  '/api/leads/$id/documents/$docId/url': typeof ApiLeadsIdDocumentsDocIdUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/agb': typeof AgbRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/freunde-werben': typeof FreundeWerbenRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/referral-request': typeof ApiReferralRequestRoute
  '/api/referral-validate': typeof ApiReferralValidateRoute
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/team': typeof ApiTeamRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/passwort-neu': typeof MitarbeiterPasswortNeuRoute
  '/mitarbeiter/passwort-vergessen': typeof MitarbeiterPasswortVergessenRoute
  '/mitarbeiter/redaktion': typeof MitarbeiterRedaktionRouteWithChildren
  '/mitarbeiter/referrals': typeof MitarbeiterReferralsRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter': typeof MitarbeiterIndexRoute
  '/api/blog/articles': typeof ApiBlogArticlesRouteWithChildren
  '/api/leads/$id': typeof ApiLeadsIdRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/team/$id': typeof ApiTeamIdRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
  '/mitarbeiter/redaktion/$id': typeof MitarbeiterRedaktionIdRoute
  '/mitarbeiter/redaktion/neu': typeof MitarbeiterRedaktionNeuRoute
  '/api/admin/blog/articles': typeof ApiAdminBlogArticlesRouteWithChildren
  '/api/blog/articles/$slug': typeof ApiBlogArticlesSlugRoute
  '/api/leads/$id/assign': typeof ApiLeadsIdAssignRoute
  '/api/leads/$id/communications': typeof ApiLeadsIdCommunicationsRoute
  '/api/leads/$id/documents': typeof ApiLeadsIdDocumentsRouteWithChildren
  '/api/leads/$id/notes': typeof ApiLeadsIdNotesRoute
  '/api/leads/$id/offers': typeof ApiLeadsIdOffersRoute
  '/api/leads/$id/status': typeof ApiLeadsIdStatusRoute
  '/api/leads/$id/status-history': typeof ApiLeadsIdStatusHistoryRoute
  '/api/referrals/$id/pay': typeof ApiReferralsIdPayRoute
  '/api/admin/blog/articles/$id': typeof ApiAdminBlogArticlesIdRoute
  '/api/leads/$id/documents/upload': typeof ApiLeadsIdDocumentsUploadRoute
  '/api/leads/$id/documents/$docId/url': typeof ApiLeadsIdDocumentsDocIdUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/agb': typeof AgbRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/freunde-werben': typeof FreundeWerbenRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitarbeiter': typeof MitarbeiterRouteWithChildren
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/referral-request': typeof ApiReferralRequestRoute
  '/api/referral-validate': typeof ApiReferralValidateRoute
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/team': typeof ApiTeamRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/passwort-neu': typeof MitarbeiterPasswortNeuRoute
  '/mitarbeiter/passwort-vergessen': typeof MitarbeiterPasswortVergessenRoute
  '/mitarbeiter/redaktion': typeof MitarbeiterRedaktionRouteWithChildren
  '/mitarbeiter/referrals': typeof MitarbeiterReferralsRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter/': typeof MitarbeiterIndexRoute
  '/api/blog/articles': typeof ApiBlogArticlesRouteWithChildren
  '/api/leads/$id': typeof ApiLeadsIdRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/team/$id': typeof ApiTeamIdRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
  '/mitarbeiter/redaktion/$id': typeof MitarbeiterRedaktionIdRoute
  '/mitarbeiter/redaktion/neu': typeof MitarbeiterRedaktionNeuRoute
  '/api/admin/blog/articles': typeof ApiAdminBlogArticlesRouteWithChildren
  '/api/blog/articles/$slug': typeof ApiBlogArticlesSlugRoute
  '/api/leads/$id/assign': typeof ApiLeadsIdAssignRoute
  '/api/leads/$id/communications': typeof ApiLeadsIdCommunicationsRoute
  '/api/leads/$id/documents': typeof ApiLeadsIdDocumentsRouteWithChildren
  '/api/leads/$id/notes': typeof ApiLeadsIdNotesRoute
  '/api/leads/$id/offers': typeof ApiLeadsIdOffersRoute
  '/api/leads/$id/status': typeof ApiLeadsIdStatusRoute
  '/api/leads/$id/status-history': typeof ApiLeadsIdStatusHistoryRoute
  '/api/referrals/$id/pay': typeof ApiReferralsIdPayRoute
  '/api/admin/blog/articles/$id': typeof ApiAdminBlogArticlesIdRoute
  '/api/leads/$id/documents/upload': typeof ApiLeadsIdDocumentsUploadRoute
  '/api/leads/$id/documents/$docId/url': typeof ApiLeadsIdDocumentsDocIdUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/agb'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/freunde-werben'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/mitarbeiter'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/api/chat'
    | '/api/leads'
    | '/api/me'
    | '/api/referral-request'
    | '/api/referral-validate'
    | '/api/referrals'
    | '/api/team'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/passwort-neu'
    | '/mitarbeiter/passwort-vergessen'
    | '/mitarbeiter/redaktion'
    | '/mitarbeiter/referrals'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter/'
    | '/api/blog/articles'
    | '/api/leads/$id'
    | '/api/public/leads'
    | '/api/team/$id'
    | '/mitarbeiter/leads/$id'
    | '/mitarbeiter/redaktion/$id'
    | '/mitarbeiter/redaktion/neu'
    | '/api/admin/blog/articles'
    | '/api/blog/articles/$slug'
    | '/api/leads/$id/assign'
    | '/api/leads/$id/communications'
    | '/api/leads/$id/documents'
    | '/api/leads/$id/notes'
    | '/api/leads/$id/offers'
    | '/api/leads/$id/status'
    | '/api/leads/$id/status-history'
    | '/api/referrals/$id/pay'
    | '/api/admin/blog/articles/$id'
    | '/api/leads/$id/documents/upload'
    | '/api/leads/$id/documents/$docId/url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/agb'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/freunde-werben'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/api/chat'
    | '/api/leads'
    | '/api/me'
    | '/api/referral-request'
    | '/api/referral-validate'
    | '/api/referrals'
    | '/api/team'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/passwort-neu'
    | '/mitarbeiter/passwort-vergessen'
    | '/mitarbeiter/redaktion'
    | '/mitarbeiter/referrals'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter'
    | '/api/blog/articles'
    | '/api/leads/$id'
    | '/api/public/leads'
    | '/api/team/$id'
    | '/mitarbeiter/leads/$id'
    | '/mitarbeiter/redaktion/$id'
    | '/mitarbeiter/redaktion/neu'
    | '/api/admin/blog/articles'
    | '/api/blog/articles/$slug'
    | '/api/leads/$id/assign'
    | '/api/leads/$id/communications'
    | '/api/leads/$id/documents'
    | '/api/leads/$id/notes'
    | '/api/leads/$id/offers'
    | '/api/leads/$id/status'
    | '/api/leads/$id/status-history'
    | '/api/referrals/$id/pay'
    | '/api/admin/blog/articles/$id'
    | '/api/leads/$id/documents/upload'
    | '/api/leads/$id/documents/$docId/url'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/agb'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/freunde-werben'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/mitarbeiter'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/api/chat'
    | '/api/leads'
    | '/api/me'
    | '/api/referral-request'
    | '/api/referral-validate'
    | '/api/referrals'
    | '/api/team'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/passwort-neu'
    | '/mitarbeiter/passwort-vergessen'
    | '/mitarbeiter/redaktion'
    | '/mitarbeiter/referrals'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter/'
    | '/api/blog/articles'
    | '/api/leads/$id'
    | '/api/public/leads'
    | '/api/team/$id'
    | '/mitarbeiter/leads/$id'
    | '/mitarbeiter/redaktion/$id'
    | '/mitarbeiter/redaktion/neu'
    | '/api/admin/blog/articles'
    | '/api/blog/articles/$slug'
    | '/api/leads/$id/assign'
    | '/api/leads/$id/communications'
    | '/api/leads/$id/documents'
    | '/api/leads/$id/notes'
    | '/api/leads/$id/offers'
    | '/api/leads/$id/status'
    | '/api/leads/$id/status-history'
    | '/api/referrals/$id/pay'
    | '/api/admin/blog/articles/$id'
    | '/api/leads/$id/documents/upload'
    | '/api/leads/$id/documents/$docId/url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  AgbRoute: typeof AgbRoute
  AngebotRoute: typeof AngebotRoute
  DankeRoute: typeof DankeRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FaqRoute: typeof FaqRoute
  FreundeWerbenRoute: typeof FreundeWerbenRoute
  GasRoute: typeof GasRoute
  GewerbegasRoute: typeof GewerbegasRoute
  GewerbestromRoute: typeof GewerbestromRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MitarbeiterRoute: typeof MitarbeiterRouteWithChildren
  ServiceRoute: typeof ServiceRoute
  SolarRoute: typeof SolarRoute
  StromRoute: typeof StromRoute
  StromGasRoute: typeof StromGasRoute
  UeberUnsRoute: typeof UeberUnsRoute
  WiderrufRoute: typeof WiderrufRoute
  WissenRoute: typeof WissenRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiReferralRequestRoute: typeof ApiReferralRequestRoute
  ApiReferralValidateRoute: typeof ApiReferralValidateRoute
  ApiReferralsRoute: typeof ApiReferralsRouteWithChildren
  ApiTeamRoute: typeof ApiTeamRouteWithChildren
  ApiBlogArticlesRoute: typeof ApiBlogArticlesRouteWithChildren
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiAdminBlogArticlesRoute: typeof ApiAdminBlogArticlesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissen': {
      id: '/wissen'
      path: '/wissen'
      fullPath: '/wissen'
      preLoaderRoute: typeof WissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strom-gas': {
      id: '/strom-gas'
      path: '/strom-gas'
      fullPath: '/strom-gas'
      preLoaderRoute: typeof StromGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strom': {
      id: '/strom'
      path: '/strom'
      fullPath: '/strom'
      preLoaderRoute: typeof StromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter': {
      id: '/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof MitarbeiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gewerbestrom': {
      id: '/gewerbestrom'
      path: '/gewerbestrom'
      fullPath: '/gewerbestrom'
      preLoaderRoute: typeof GewerbestromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gewerbegas': {
      id: '/gewerbegas'
      path: '/gewerbegas'
      fullPath: '/gewerbegas'
      preLoaderRoute: typeof GewerbegasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas': {
      id: '/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof GasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freunde-werben': {
      id: '/freunde-werben'
      path: '/freunde-werben'
      fullPath: '/freunde-werben'
      preLoaderRoute: typeof FreundeWerbenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danke': {
      id: '/danke'
      path: '/danke'
      fullPath: '/danke'
      preLoaderRoute: typeof DankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot': {
      id: '/angebot'
      path: '/angebot'
      fullPath: '/angebot'
      preLoaderRoute: typeof AngebotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter/': {
      id: '/mitarbeiter/'
      path: '/'
      fullPath: '/mitarbeiter/'
      preLoaderRoute: typeof MitarbeiterIndexRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/wissen/$slug': {
      id: '/wissen/$slug'
      path: '/$slug'
      fullPath: '/wissen/$slug'
      preLoaderRoute: typeof WissenSlugRouteImport
      parentRoute: typeof WissenRoute
    }
    '/mitarbeiter/wiedervorlage': {
      id: '/mitarbeiter/wiedervorlage'
      path: '/wiedervorlage'
      fullPath: '/mitarbeiter/wiedervorlage'
      preLoaderRoute: typeof MitarbeiterWiedervorlageRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/vorlagen': {
      id: '/mitarbeiter/vorlagen'
      path: '/vorlagen'
      fullPath: '/mitarbeiter/vorlagen'
      preLoaderRoute: typeof MitarbeiterVorlagenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/team': {
      id: '/mitarbeiter/team'
      path: '/team'
      fullPath: '/mitarbeiter/team'
      preLoaderRoute: typeof MitarbeiterTeamRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/tarife': {
      id: '/mitarbeiter/tarife'
      path: '/tarife'
      fullPath: '/mitarbeiter/tarife'
      preLoaderRoute: typeof MitarbeiterTarifeRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/statistiken': {
      id: '/mitarbeiter/statistiken'
      path: '/statistiken'
      fullPath: '/mitarbeiter/statistiken'
      preLoaderRoute: typeof MitarbeiterStatistikenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/referrals': {
      id: '/mitarbeiter/referrals'
      path: '/referrals'
      fullPath: '/mitarbeiter/referrals'
      preLoaderRoute: typeof MitarbeiterReferralsRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/redaktion': {
      id: '/mitarbeiter/redaktion'
      path: '/redaktion'
      fullPath: '/mitarbeiter/redaktion'
      preLoaderRoute: typeof MitarbeiterRedaktionRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/passwort-vergessen': {
      id: '/mitarbeiter/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/mitarbeiter/passwort-vergessen'
      preLoaderRoute: typeof MitarbeiterPasswortVergessenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/passwort-neu': {
      id: '/mitarbeiter/passwort-neu'
      path: '/passwort-neu'
      fullPath: '/mitarbeiter/passwort-neu'
      preLoaderRoute: typeof MitarbeiterPasswortNeuRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/login': {
      id: '/mitarbeiter/login'
      path: '/login'
      fullPath: '/mitarbeiter/login'
      preLoaderRoute: typeof MitarbeiterLoginRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/leads': {
      id: '/mitarbeiter/leads'
      path: '/leads'
      fullPath: '/mitarbeiter/leads'
      preLoaderRoute: typeof MitarbeiterLeadsRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/kunden': {
      id: '/mitarbeiter/kunden'
      path: '/kunden'
      fullPath: '/mitarbeiter/kunden'
      preLoaderRoute: typeof MitarbeiterKundenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/einstellungen': {
      id: '/mitarbeiter/einstellungen'
      path: '/einstellungen'
      fullPath: '/mitarbeiter/einstellungen'
      preLoaderRoute: typeof MitarbeiterEinstellungenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/dashboard': {
      id: '/mitarbeiter/dashboard'
      path: '/dashboard'
      fullPath: '/mitarbeiter/dashboard'
      preLoaderRoute: typeof MitarbeiterDashboardRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/anbieter': {
      id: '/mitarbeiter/anbieter'
      path: '/anbieter'
      fullPath: '/mitarbeiter/anbieter'
      preLoaderRoute: typeof MitarbeiterAnbieterRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/api/team': {
      id: '/api/team'
      path: '/api/team'
      fullPath: '/api/team'
      preLoaderRoute: typeof ApiTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral-validate': {
      id: '/api/referral-validate'
      path: '/api/referral-validate'
      fullPath: '/api/referral-validate'
      preLoaderRoute: typeof ApiReferralValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral-request': {
      id: '/api/referral-request'
      path: '/api/referral-request'
      fullPath: '/api/referral-request'
      preLoaderRoute: typeof ApiReferralRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter/redaktion/neu': {
      id: '/mitarbeiter/redaktion/neu'
      path: '/neu'
      fullPath: '/mitarbeiter/redaktion/neu'
      preLoaderRoute: typeof MitarbeiterRedaktionNeuRouteImport
      parentRoute: typeof MitarbeiterRedaktionRoute
    }
    '/mitarbeiter/redaktion/$id': {
      id: '/mitarbeiter/redaktion/$id'
      path: '/$id'
      fullPath: '/mitarbeiter/redaktion/$id'
      preLoaderRoute: typeof MitarbeiterRedaktionIdRouteImport
      parentRoute: typeof MitarbeiterRedaktionRoute
    }
    '/mitarbeiter/leads/$id': {
      id: '/mitarbeiter/leads/$id'
      path: '/$id'
      fullPath: '/mitarbeiter/leads/$id'
      preLoaderRoute: typeof MitarbeiterLeadsIdRouteImport
      parentRoute: typeof MitarbeiterLeadsRoute
    }
    '/api/team/$id': {
      id: '/api/team/$id'
      path: '/$id'
      fullPath: '/api/team/$id'
      preLoaderRoute: typeof ApiTeamIdRouteImport
      parentRoute: typeof ApiTeamRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/$id': {
      id: '/api/leads/$id'
      path: '/$id'
      fullPath: '/api/leads/$id'
      preLoaderRoute: typeof ApiLeadsIdRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/blog/articles': {
      id: '/api/blog/articles'
      path: '/api/blog/articles'
      fullPath: '/api/blog/articles'
      preLoaderRoute: typeof ApiBlogArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/$id/pay': {
      id: '/api/referrals/$id/pay'
      path: '/$id/pay'
      fullPath: '/api/referrals/$id/pay'
      preLoaderRoute: typeof ApiReferralsIdPayRouteImport
      parentRoute: typeof ApiReferralsRoute
    }
    '/api/leads/$id/status-history': {
      id: '/api/leads/$id/status-history'
      path: '/status-history'
      fullPath: '/api/leads/$id/status-history'
      preLoaderRoute: typeof ApiLeadsIdStatusHistoryRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/status': {
      id: '/api/leads/$id/status'
      path: '/status'
      fullPath: '/api/leads/$id/status'
      preLoaderRoute: typeof ApiLeadsIdStatusRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/offers': {
      id: '/api/leads/$id/offers'
      path: '/offers'
      fullPath: '/api/leads/$id/offers'
      preLoaderRoute: typeof ApiLeadsIdOffersRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/notes': {
      id: '/api/leads/$id/notes'
      path: '/notes'
      fullPath: '/api/leads/$id/notes'
      preLoaderRoute: typeof ApiLeadsIdNotesRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/documents': {
      id: '/api/leads/$id/documents'
      path: '/documents'
      fullPath: '/api/leads/$id/documents'
      preLoaderRoute: typeof ApiLeadsIdDocumentsRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/communications': {
      id: '/api/leads/$id/communications'
      path: '/communications'
      fullPath: '/api/leads/$id/communications'
      preLoaderRoute: typeof ApiLeadsIdCommunicationsRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/leads/$id/assign': {
      id: '/api/leads/$id/assign'
      path: '/assign'
      fullPath: '/api/leads/$id/assign'
      preLoaderRoute: typeof ApiLeadsIdAssignRouteImport
      parentRoute: typeof ApiLeadsIdRoute
    }
    '/api/blog/articles/$slug': {
      id: '/api/blog/articles/$slug'
      path: '/$slug'
      fullPath: '/api/blog/articles/$slug'
      preLoaderRoute: typeof ApiBlogArticlesSlugRouteImport
      parentRoute: typeof ApiBlogArticlesRoute
    }
    '/api/admin/blog/articles': {
      id: '/api/admin/blog/articles'
      path: '/api/admin/blog/articles'
      fullPath: '/api/admin/blog/articles'
      preLoaderRoute: typeof ApiAdminBlogArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/$id/documents/upload': {
      id: '/api/leads/$id/documents/upload'
      path: '/upload'
      fullPath: '/api/leads/$id/documents/upload'
      preLoaderRoute: typeof ApiLeadsIdDocumentsUploadRouteImport
      parentRoute: typeof ApiLeadsIdDocumentsRoute
    }
    '/api/admin/blog/articles/$id': {
      id: '/api/admin/blog/articles/$id'
      path: '/$id'
      fullPath: '/api/admin/blog/articles/$id'
      preLoaderRoute: typeof ApiAdminBlogArticlesIdRouteImport
      parentRoute: typeof ApiAdminBlogArticlesRoute
    }
    '/api/leads/$id/documents/$docId/url': {
      id: '/api/leads/$id/documents/$docId/url'
      path: '/$docId/url'
      fullPath: '/api/leads/$id/documents/$docId/url'
      preLoaderRoute: typeof ApiLeadsIdDocumentsDocIdUrlRouteImport
      parentRoute: typeof ApiLeadsIdDocumentsRoute
    }
  }
}

interface MitarbeiterLeadsRouteChildren {
  MitarbeiterLeadsIdRoute: typeof MitarbeiterLeadsIdRoute
}

const MitarbeiterLeadsRouteChildren: MitarbeiterLeadsRouteChildren = {
  MitarbeiterLeadsIdRoute: MitarbeiterLeadsIdRoute,
}

const MitarbeiterLeadsRouteWithChildren =
  MitarbeiterLeadsRoute._addFileChildren(MitarbeiterLeadsRouteChildren)

interface MitarbeiterRedaktionRouteChildren {
  MitarbeiterRedaktionIdRoute: typeof MitarbeiterRedaktionIdRoute
  MitarbeiterRedaktionNeuRoute: typeof MitarbeiterRedaktionNeuRoute
}

const MitarbeiterRedaktionRouteChildren: MitarbeiterRedaktionRouteChildren = {
  MitarbeiterRedaktionIdRoute: MitarbeiterRedaktionIdRoute,
  MitarbeiterRedaktionNeuRoute: MitarbeiterRedaktionNeuRoute,
}

const MitarbeiterRedaktionRouteWithChildren =
  MitarbeiterRedaktionRoute._addFileChildren(MitarbeiterRedaktionRouteChildren)

interface MitarbeiterRouteChildren {
  MitarbeiterAnbieterRoute: typeof MitarbeiterAnbieterRoute
  MitarbeiterDashboardRoute: typeof MitarbeiterDashboardRoute
  MitarbeiterEinstellungenRoute: typeof MitarbeiterEinstellungenRoute
  MitarbeiterKundenRoute: typeof MitarbeiterKundenRoute
  MitarbeiterLeadsRoute: typeof MitarbeiterLeadsRouteWithChildren
  MitarbeiterLoginRoute: typeof MitarbeiterLoginRoute
  MitarbeiterPasswortNeuRoute: typeof MitarbeiterPasswortNeuRoute
  MitarbeiterPasswortVergessenRoute: typeof MitarbeiterPasswortVergessenRoute
  MitarbeiterRedaktionRoute: typeof MitarbeiterRedaktionRouteWithChildren
  MitarbeiterReferralsRoute: typeof MitarbeiterReferralsRoute
  MitarbeiterStatistikenRoute: typeof MitarbeiterStatistikenRoute
  MitarbeiterTarifeRoute: typeof MitarbeiterTarifeRoute
  MitarbeiterTeamRoute: typeof MitarbeiterTeamRoute
  MitarbeiterVorlagenRoute: typeof MitarbeiterVorlagenRoute
  MitarbeiterWiedervorlageRoute: typeof MitarbeiterWiedervorlageRoute
  MitarbeiterIndexRoute: typeof MitarbeiterIndexRoute
}

const MitarbeiterRouteChildren: MitarbeiterRouteChildren = {
  MitarbeiterAnbieterRoute: MitarbeiterAnbieterRoute,
  MitarbeiterDashboardRoute: MitarbeiterDashboardRoute,
  MitarbeiterEinstellungenRoute: MitarbeiterEinstellungenRoute,
  MitarbeiterKundenRoute: MitarbeiterKundenRoute,
  MitarbeiterLeadsRoute: MitarbeiterLeadsRouteWithChildren,
  MitarbeiterLoginRoute: MitarbeiterLoginRoute,
  MitarbeiterPasswortNeuRoute: MitarbeiterPasswortNeuRoute,
  MitarbeiterPasswortVergessenRoute: MitarbeiterPasswortVergessenRoute,
  MitarbeiterRedaktionRoute: MitarbeiterRedaktionRouteWithChildren,
  MitarbeiterReferralsRoute: MitarbeiterReferralsRoute,
  MitarbeiterStatistikenRoute: MitarbeiterStatistikenRoute,
  MitarbeiterTarifeRoute: MitarbeiterTarifeRoute,
  MitarbeiterTeamRoute: MitarbeiterTeamRoute,
  MitarbeiterVorlagenRoute: MitarbeiterVorlagenRoute,
  MitarbeiterWiedervorlageRoute: MitarbeiterWiedervorlageRoute,
  MitarbeiterIndexRoute: MitarbeiterIndexRoute,
}

const MitarbeiterRouteWithChildren = MitarbeiterRoute._addFileChildren(
  MitarbeiterRouteChildren,
)

interface WissenRouteChildren {
  WissenSlugRoute: typeof WissenSlugRoute
}

const WissenRouteChildren: WissenRouteChildren = {
  WissenSlugRoute: WissenSlugRoute,
}

const WissenRouteWithChildren =
  WissenRoute._addFileChildren(WissenRouteChildren)

interface ApiLeadsIdDocumentsRouteChildren {
  ApiLeadsIdDocumentsUploadRoute: typeof ApiLeadsIdDocumentsUploadRoute
  ApiLeadsIdDocumentsDocIdUrlRoute: typeof ApiLeadsIdDocumentsDocIdUrlRoute
}

const ApiLeadsIdDocumentsRouteChildren: ApiLeadsIdDocumentsRouteChildren = {
  ApiLeadsIdDocumentsUploadRoute: ApiLeadsIdDocumentsUploadRoute,
  ApiLeadsIdDocumentsDocIdUrlRoute: ApiLeadsIdDocumentsDocIdUrlRoute,
}

const ApiLeadsIdDocumentsRouteWithChildren =
  ApiLeadsIdDocumentsRoute._addFileChildren(ApiLeadsIdDocumentsRouteChildren)

interface ApiLeadsIdRouteChildren {
  ApiLeadsIdAssignRoute: typeof ApiLeadsIdAssignRoute
  ApiLeadsIdCommunicationsRoute: typeof ApiLeadsIdCommunicationsRoute
  ApiLeadsIdDocumentsRoute: typeof ApiLeadsIdDocumentsRouteWithChildren
  ApiLeadsIdNotesRoute: typeof ApiLeadsIdNotesRoute
  ApiLeadsIdOffersRoute: typeof ApiLeadsIdOffersRoute
  ApiLeadsIdStatusRoute: typeof ApiLeadsIdStatusRoute
  ApiLeadsIdStatusHistoryRoute: typeof ApiLeadsIdStatusHistoryRoute
}

const ApiLeadsIdRouteChildren: ApiLeadsIdRouteChildren = {
  ApiLeadsIdAssignRoute: ApiLeadsIdAssignRoute,
  ApiLeadsIdCommunicationsRoute: ApiLeadsIdCommunicationsRoute,
  ApiLeadsIdDocumentsRoute: ApiLeadsIdDocumentsRouteWithChildren,
  ApiLeadsIdNotesRoute: ApiLeadsIdNotesRoute,
  ApiLeadsIdOffersRoute: ApiLeadsIdOffersRoute,
  ApiLeadsIdStatusRoute: ApiLeadsIdStatusRoute,
  ApiLeadsIdStatusHistoryRoute: ApiLeadsIdStatusHistoryRoute,
}

const ApiLeadsIdRouteWithChildren = ApiLeadsIdRoute._addFileChildren(
  ApiLeadsIdRouteChildren,
)

interface ApiLeadsRouteChildren {
  ApiLeadsIdRoute: typeof ApiLeadsIdRouteWithChildren
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsIdRoute: ApiLeadsIdRouteWithChildren,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

interface ApiReferralsRouteChildren {
  ApiReferralsIdPayRoute: typeof ApiReferralsIdPayRoute
}

const ApiReferralsRouteChildren: ApiReferralsRouteChildren = {
  ApiReferralsIdPayRoute: ApiReferralsIdPayRoute,
}

const ApiReferralsRouteWithChildren = ApiReferralsRoute._addFileChildren(
  ApiReferralsRouteChildren,
)

interface ApiTeamRouteChildren {
  ApiTeamIdRoute: typeof ApiTeamIdRoute
}

const ApiTeamRouteChildren: ApiTeamRouteChildren = {
  ApiTeamIdRoute: ApiTeamIdRoute,
}

const ApiTeamRouteWithChildren =
  ApiTeamRoute._addFileChildren(ApiTeamRouteChildren)

interface ApiBlogArticlesRouteChildren {
  ApiBlogArticlesSlugRoute: typeof ApiBlogArticlesSlugRoute
}

const ApiBlogArticlesRouteChildren: ApiBlogArticlesRouteChildren = {
  ApiBlogArticlesSlugRoute: ApiBlogArticlesSlugRoute,
}

const ApiBlogArticlesRouteWithChildren = ApiBlogArticlesRoute._addFileChildren(
  ApiBlogArticlesRouteChildren,
)

interface ApiAdminBlogArticlesRouteChildren {
  ApiAdminBlogArticlesIdRoute: typeof ApiAdminBlogArticlesIdRoute
}

const ApiAdminBlogArticlesRouteChildren: ApiAdminBlogArticlesRouteChildren = {
  ApiAdminBlogArticlesIdRoute: ApiAdminBlogArticlesIdRoute,
}

const ApiAdminBlogArticlesRouteWithChildren =
  ApiAdminBlogArticlesRoute._addFileChildren(ApiAdminBlogArticlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  AgbRoute: AgbRoute,
  AngebotRoute: AngebotRoute,
  DankeRoute: DankeRoute,
  DatenschutzRoute: DatenschutzRoute,
  FaqRoute: FaqRoute,
  FreundeWerbenRoute: FreundeWerbenRoute,
  GasRoute: GasRoute,
  GewerbegasRoute: GewerbegasRoute,
  GewerbestromRoute: GewerbestromRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MitarbeiterRoute: MitarbeiterRouteWithChildren,
  ServiceRoute: ServiceRoute,
  SolarRoute: SolarRoute,
  StromRoute: StromRoute,
  StromGasRoute: StromGasRoute,
  UeberUnsRoute: UeberUnsRoute,
  WiderrufRoute: WiderrufRoute,
  WissenRoute: WissenRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiReferralRequestRoute: ApiReferralRequestRoute,
  ApiReferralValidateRoute: ApiReferralValidateRoute,
  ApiReferralsRoute: ApiReferralsRouteWithChildren,
  ApiTeamRoute: ApiTeamRouteWithChildren,
  ApiBlogArticlesRoute: ApiBlogArticlesRouteWithChildren,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiAdminBlogArticlesRoute: ApiAdminBlogArticlesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
