INSERT INTO public.blog_articles (slug, title, teaser, image, tag, author, body, read_time_min, is_published, published_at)
VALUES
(
  'strompreis-2026',
  'Strompreis 2026: Was Haushalte jetzt wissen müssen',
  'Netzentgelte steigen, CO₂-Preis zieht an, aber Großhandelspreise sinken. Was bedeutet das für Ihre nächste Jahresabrechnung?',
  'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=630&fit=crop&q=80',
  'Strom',
  'Sarah Becker',
  '[{"heading":"Die wichtigsten Trends 2026","paragraphs":["Im Jahr 2026 stehen Haushalte vor einer paradoxen Situation: Während die Beschaffungskosten an der Strombörse leicht sinken, steigen die regulatorischen Kosten. Allen voran Netzentgelte und CO₂-Preis. Für den durchschnittlichen Haushalt mit 3.500 kWh Jahresverbrauch bedeutet das eine Mehrbelastung von rund 70 €.","Wer bisher in der Grundversorgung ist, zahlt im Schnitt 14–22 % mehr als Wechselkunden bei einem Sondertarif. Ein Anbieterwechsel bleibt damit der wirksamste Einzelhebel für die Stromrechnung."]},{"heading":"Worauf jetzt achten","paragraphs":["Preisgarantien sind 2026 wieder ein zentrales Kriterium. Tarife mit 12 oder besser 24 Monaten echter Preisgarantie schützen vor weiteren Strompreissprüngen. Vorsicht: Manche Anbieter werben mit eingeschränkter Preisgarantie, die Netzentgelte ausnimmt.","Bonuszahlungen sind verlockend, aber rechnen Sie immer die Kosten ohne Bonus durch. Ein Tarif mit 250 € Sofortbonus, der nach 12 Monaten in einen teuren Folgetarif übergeht, ist oft teurer als ein Tarif ohne Bonus mit fairer Folgekonditionierung."]},{"heading":"Unsere Empfehlung","paragraphs":["Lassen Sie alle 12 Monate prüfen, ob Ihr Tarif noch passt. Das geht in unter 2 Minuten und kann mehrere hundert Euro sparen. Ohne Aufwand, ohne Versorgungslücke."]}]'::jsonb,
  8, true, '2026-06-12 00:00:00+00'
),
(
  'oekostrom-labels',
  'Ökostrom erkennen: Echte Labels im Vergleich',
  'OK-Power, Grüner Strom-Label, TÜV Süd EE01. Welches Siegel garantiert wirklich neuen Ökostrom?',
  'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&h=630&fit=crop&q=80',
  'Strom',
  'Daniel Kraus',
  '[{"heading":"Was ist überhaupt Ökostrom?","paragraphs":["Ökostrom ist nicht gleich Ökostrom. Der Begriff selbst ist nicht geschützt. Anbieter können auch dann Ökostrom verkaufen, wenn sie selbst keinen einzigen Cent in neue Anlagen investieren.","Echte Wirkung entsteht nur, wenn der Tarif den Ausbau erneuerbarer Energien in Deutschland aktiv fördert. Das Schlüsselinstrument dafür sind unabhängige Zertifizierungen."]},{"heading":"Die wichtigsten Siegel im Überblick","paragraphs":["Das Grüner Strom-Label gilt als das strengste Label auf dem Markt. Anbieter müssen nachweisen, dass ein fester Anteil des Umsatzes direkt in neue Anlagen investiert wird — mindestens 0,1 Cent pro kWh.","OK-Power ist ebenfalls ein anerkanntes Siegel. Es schreibt vor, dass mindestens 5 % der Strommenge aus Neuanlagen stammen müssen, die nicht älter als 6 Jahre sind."]},{"heading":"Labels die Sie meiden sollten","paragraphs":["Tarife, die nur mit dem Herkunftsnachweissystem (RECS/HKN) arbeiten, fördern keinen einzigen Cent neue Kapazität. Der Strom ist rechnerisch grün, hat aber keinen Zusatznutzen für die Energiewende.","Prüfen Sie immer: Steht ein unabhängiges Institut hinter dem Label? Wird die Zertifizierung jährlich erneuert? Ist der Prüfbericht öffentlich einsehbar?"]},{"heading":"Unser Fazit","paragraphs":["Wählen Sie Tarife mit Grüner Strom-Label oder OK-Power, wenn echte Klimawirkung Ihr Ziel ist. Beide Siegel sind unabhängig geprüft und stehen für nachweisbaren Ausbau erneuerbarer Energien in Deutschland."]}]'::jsonb,
  7, true, '2026-06-08 00:00:00+00'
),
(
  'gaspreise-2026',
  'Gaspreise 2026: Prognose & Spar-Tipps',
  'Wie sich der Gaspreis im kommenden Heizjahr entwickeln dürfte. Und wann sich ein Festpreis lohnt.',
  'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?w=1200&h=630&fit=crop&q=80',
  'Gas',
  'Mira Aydin',
  '[{"heading":"Wo stehen wir 2026?","paragraphs":["Die Gaspreise haben sich nach den Höchstständen 2022/23 stabilisiert, liegen aber weiter deutlich über dem Vor-Krisen-Niveau. Der Durchschnittspreis für Haushaltskunden liegt 2026 bei 9–11 Cent pro kWh.","Entscheidend für die Preisentwicklung bleiben die europäischen Füllstände der Gasspeicher sowie die globale LNG-Nachfrage. Beide Faktoren sorgen aktuell für ein moderates Preisniveau."]},{"heading":"Festpreis oder variabler Tarif?","paragraphs":["Bei aktuell stabilen Marktpreisen spricht vieles für einen Festpreistarif mit 12 oder 24 Monaten Laufzeit. So sichern Sie sich das aktuelle Niveau und sind vor saisonalen Preissprüngen im Winter geschützt.","Variable Tarife folgen dem Markt — sie können günstiger sein, wenn die Preise fallen, aber auch deutlich teurer, wenn geopolitische Ereignisse den Markt bewegen."]},{"heading":"So sparen Sie am meisten","paragraphs":["Der wirksamste Hebel bleibt der Anbieterwechsel. Wer noch im Grundversorger-Tarif ist, zahlt durchschnittlich 15–25 % mehr als bei einem Wechselanbieter. Ein Vergleich dauert 2 Minuten und kann 200–400 € pro Jahr sparen.","Kombinieren Sie den Tarifwechsel mit technischen Maßnahmen: Hydraulischer Abgleich, Nachtabsenkung und richtige Thermostateinstellung können den Gasverbrauch um 10–20 % senken."]},{"heading":"Unsere Empfehlung für 2026","paragraphs":["Jetzt wechseln, Festpreis für 24 Monate sichern. Die Marktlage ist günstig, die Angebote sind wettbewerbsintensiv. Wer wartet, riskiert steigende Preise zum Herbst hin."]}]'::jsonb,
  8, true, '2026-06-05 00:00:00+00'
),
(
  'solaranlage-kosten-2026',
  'Solaranlage-Kosten 2026: Alles auf einen Blick',
  'Was Sie heute für eine 10-kWp-Anlage zahlen, wie schnell sie sich rechnet und welche Förderung greift.',
  'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1200&h=630&fit=crop&q=80',
  'Solar',
  'Sarah Becker',
  '[{"heading":"Aktuelle Preise für Solaranlagen 2026","paragraphs":["Eine schlüsselfertige 10-kWp-Anlage kostet 2026 zwischen 13.000 € und 18.000 €, inklusive Wechselrichter und Montage. Das entspricht einem Preis von 1.300–1.800 € pro kWp — ein historischer Tiefstand.","Gegenüber 2020 sind die Modulpreise um über 60 % gefallen. Die Lernkurve der Photovoltaik-Industrie hält an, weitere moderate Preisrückgänge sind in den nächsten Jahren zu erwarten."]},{"heading":"Amortisation und Rendite","paragraphs":["Bei einem Eigenverbrauchsanteil von 30–40 % und einem Haushaltsstrompreis von 28–32 Cent/kWh amortisiert sich eine 10-kWp-Anlage in 8–11 Jahren. Die Lebenserwartung beträgt 25–30 Jahre.","Mit Batteriespeicher verlängert sich die Amortisationszeit um 2–4 Jahre, aber der Eigenverbrauchsanteil steigt auf 60–80 %. Ob das wirtschaftlich ist, hängt stark vom Nutzungsverhalten ab."]},{"heading":"Förderung und Steuervorteile","paragraphs":["Seit 2023 gilt für Solaranlagen bis 30 kWp Umsatzsteuerbefreiung (0 % USt.). Das spart bei einer 10-kWp-Anlage rund 2.000–3.000 € gegenüber dem Vorjahr.","Die KfW fördert mit zinsgünstigen Krediten (Programm 270) ab 0,5 % effektivem Jahreszins. Kombiniert mit BAFA-Zuschüssen für Stromspeicher ergibt sich eine attraktive Gesamtförderung."]},{"heading":"Worauf beim Angebot achten","paragraphs":["Vergleichen Sie immer mindestens 3 Angebote. Achten Sie auf Markenhersteller bei Modulen und Wechselrichter sowie auf Garantiezeiten: 25 Jahre Leistungsgarantie auf die Module sind heute Standard.","Fragen Sie explizit nach dem Dachdurchführungskonzept und der Blitzschutzkonzeption. Viele günstige Angebote sparen genau hier."]},{"heading":"Unser Fazit","paragraphs":["2026 ist ein ausgezeichneter Zeitpunkt für eine Solarinvestition. Niedrige Modulpreise, gute Förderkulisse und hohe Strompreise machen die Rechnung attraktiver denn je."]}]'::jsonb,
  10, true, '2026-06-01 00:00:00+00'
),
(
  'bundle-doppelbonus',
  'Strom & Gas bündeln: Wann sich der Doppel-Bonus lohnt',
  'Bundles können doppelt sparen. Oder nichts bringen. Diese drei Fragen entscheiden.',
  'https://images.unsplash.com/photo-1548502032-4d0e6d99b31e?w=1200&h=630&fit=crop&q=80',
  'Strom & Gas',
  'Daniel Kraus',
  '[{"heading":"Was ist ein Bundle-Tarif?","paragraphs":["Ein Bundle-Tarif bündelt Strom und Gas in einem einzigen Vertrag mit einem Anbieter. Das klingt zunächst praktisch: eine Rechnung, ein Ansprechpartner, ein Lastschrifteinzug.","Viele Anbieter locken mit Doppel-Boni von 200–400 €, wenn beide Sparten gleichzeitig gewechselt werden. Doch ob sich das wirklich lohnt, hängt von drei Faktoren ab."]},{"heading":"Frage 1: Sind die Einzeltarife auch ohne Bundle gut?","paragraphs":["Rechnen Sie die Tarife immer separat durch. Manchmal ist ein Bundle-Angebot nur deshalb günstiger, weil ein Einzeltarif besonders teuer angesetzt ist. Ein fairer Vergleich zeigt: Der Strom-Einzeltarif X + Gas-Einzeltarif Y kann günstiger sein als das Bundle.","Prüfen Sie auch den Folgetarif nach Ablauf der Erstlaufzeit. Manche Anbieter locken mit günstigen Einstiegspreisen und erhöhen nach 12 Monaten deutlich."]},{"heading":"Frage 2: Laufen beide Verträge synchron aus?","paragraphs":["Wenn Sie bereits einen laufenden Stromvertrag haben, beginnt der neue Gasvertrag zu einem anderen Zeitpunkt. Das erschwert spätere Verhandlungen und Wechsel.","Ideal sind Bundles, bei denen beide Laufzeiten parallel starten und enden. So können Sie bei der nächsten Verlängerung beide auf einmal neu verhandeln."]},{"heading":"Frage 3: Gibt es einen echten Doppelbonus?","paragraphs":["Echte Doppelboni werden von seriösen Anbietern in den AGB klar ausgewiesen. Prüfen Sie: Wann wird ausgezahlt? Gibt es Mindestlaufzeiten? Gilt der Bonus für beide Sparten oder nur eine?","Faustregel: Ein echter Doppelbonus ab 150 € (je 75 € pro Sparte) macht ein Bundle interessant — wenn die Grundpreise marktgerecht sind."]}]'::jsonb,
  6, true, '2026-05-28 00:00:00+00'
),
(
  'waermestrom-tarif',
  'Wärmestrom: Wann sich ein Sondertarif rechnet',
  'Wärmepumpe oder Nachtspeicher? Wir zeigen, ab wann ein separater Wärmestromzähler Sinn ergibt.',
  'https://images.unsplash.com/photo-1558618047-3c8c5a00b1c2?w=1200&h=630&fit=crop&q=80',
  'Strom',
  'Mira Aydin',
  '[{"heading":"Was ist Wärmestrom?","paragraphs":["Wärmestrom ist ein Sonderstromtarif für elektrisch betriebene Heizanlagen — also Wärmepumpen, Nachtspeicherheizungen oder Direktheizungen. Die Idee: Da diese Anlagen besonders viel Strom verbrauchen, bekommen Nutzer einen günstigeren Arbeitspreis.","Technische Voraussetzung ist ein separater Wärmestromzähler und eine steuerbare Verbrauchseinrichtung. Das bedeutet: Der Netzbetreiber kann in Spitzenlastzeiten die Heizung kurzzeitig abschalten — in der Praxis meist 2-mal täglich für maximal 2 Stunden."]},{"heading":"Lohnt sich ein eigener Wärmestromzähler?","paragraphs":["Die Antwort hängt vom Jahresverbrauch ab. Bei Wärmepumpen mit 6.000 kWh Jahresverbrauch oder mehr rechnet sich der Sondertarif fast immer. Die Ersparnis gegenüber dem Normalstromtarif beträgt typischerweise 3–7 Cent pro kWh.","Bei kleineren Nachtspeicherheizungen oder Hybridlösungen sollten Sie den Mehraufwand (Zählerinstallation, oft 200–400 €) gegen die jährliche Ersparnis abwägen."]},{"heading":"So beantragen Sie Wärmestrom","paragraphs":["Der Antrag läuft über Ihren Netzbetreiber, nicht über den Stromlieferanten. Beantragen Sie zuerst den separaten Zähler beim Netzbetreiber, dann wählen Sie den Wärmestromtarif bei einem Anbieter Ihrer Wahl.","EnergieClever vergleicht Wärmestromtarife und findet das günstigste Angebot für Ihre Anlage und Ihren Standort."]},{"heading":"Wärmepumpe 2026: Das richtige Tarifen ist entscheidend","paragraphs":["Mit der zunehmenden Verbreitung von Wärmepumpen wächst auch der Wettbewerb unter Wärmestromanbietern. Besonders attraktiv sind dynamische Tarife, die den günstigsten Strom nutzen, wenn Solarstrom im Netz überschüssig ist — oft unter 15 Cent pro kWh."]}]'::jsonb,
  7, true, '2026-05-22 00:00:00+00'
),
(
  'e-auto-laden',
  'E-Auto laden zuhause: Der günstigste Weg',
  'Autostromtarif, dynamischer Tarif oder einfach Haushaltsstrom? Eine Entscheidungshilfe.',
  'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1200&h=630&fit=crop&q=80',
  'Strom',
  'Sarah Becker',
  '[{"heading":"Wie viel Strom braucht ein E-Auto?","paragraphs":["Ein durchschnittliches Elektroauto verbraucht etwa 15–20 kWh pro 100 km. Bei 15.000 km Jahresfahrleistung sind das 2.250–3.000 kWh — also fast so viel wie ein Haushalt mit zwei Personen.","Diese Zusatzlast macht deutlich: Ein normaler Haushaltsstromtarif kann für E-Auto-Fahrer suboptimal sein. Es gibt bessere Optionen."]},{"heading":"Option 1: Autostromtarif","paragraphs":["Viele Anbieter haben spezielle Autostromtarife entwickelt, die günstigere Nachtladezeiten bieten. Typisch: 15–20 Cent/kWh nachts statt 28–32 Cent tagsüber.","Voraussetzung ist oft ein intelligentes Messsystem (Smart Meter) und eine steuerbare Wallbox. Der Netzbetreiber kann die Ladung in Spitzenlastzeiten kurz unterbrechen."]},{"heading":"Option 2: Dynamischer Stromtarif","paragraphs":["Dynamische Tarife folgen dem Börsenstrompreis stündlich. Wer flexibel laden kann — nachts oder wenn Solarstrom im Überfluss vorhanden ist — zahlt manchmal unter 10 Cent/kWh.","Der Haken: Die Abrechnung ist komplex, und in Hochpreisphasen kann der Strom teuer werden. Ohne Smart-Home-Steuerung ist diese Option schwer manuell zu managen."]},{"heading":"Option 3: Einfach Haushaltsstrom","paragraphs":["Für viele Fahrer mit moderatem Jahreskilometerstand (unter 10.000 km) ist ein günstiger Haushaltsstromtarif die unkomplizierteste Lösung. Die Ersparnis durch Spezialtarife übersteigt selten 150 € pro Jahr — der Aufwand für separate Zähler und Verträge muss sich lohnen."]},{"heading":"Unser Tipp","paragraphs":["Ab 12.000 km Jahresfahrleistung lohnt sich ein Autostromtarif fast immer. Darunter genügt ein günstiger Haushaltsstromtarif. EnergieClever vergleicht beide Varianten und zeigt Ihnen, welche Option für Ihr Fahrprofil günstiger ist."]}]'::jsonb,
  8, true, '2026-05-18 00:00:00+00'
),
(
  'heizkosten-senken',
  'Heizkosten senken: 7 schnelle Maßnahmen',
  'Hohe Gasrechnung? Mit diesen 7 einfachen Tipps können Sie Ihre Heizkosten sofort senken — ohne großen Aufwand.',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=630&fit=crop&q=80',
  'Gas',
  'EnergieClever Redaktion',
  '[{"heading":"Thermostat richtig einstellen","paragraphs":["Die Heizkurve beschreibt, wie stark Ihre Heizanlage auf Außentemperaturen reagiert. Viele Anlagen sind ab Werk zu hoch eingestellt — eine Absenkung um eine Stufe spart 6–10 % Heizenergie, ohne dass Sie Komforteinbußen spüren.","Die ideale Raumtemperatur liegt im Wohnbereich bei 20–21 °C, im Schlafzimmer bei 16–18 °C. Jedes Grad weniger spart rund 6 % Heizkosten."]},{"heading":"Hydraulischen Abgleich durchführen lassen","paragraphs":["Beim hydraulischen Abgleich wird die Wassermenge, die durch jeden Heizkörper fließt, präzise eingestellt. Das Ergebnis: Alle Räume werden gleichmäßig warm, die Heizung läuft effizienter.","Seit 2023 ist der hydraulische Abgleich für Gebäude mit zentraler Gasheizung Pflicht, wenn staatliche Fördermittel in Anspruch genommen werden. Kosten: 300–800 € je nach Hausgröße, Amortisation in 1–3 Jahren."]},{"heading":"Nachtabsenkung und Zeitprogramme nutzen","paragraphs":["Moderne Heizungssteuerungen erlauben es, die Temperatur nachts und tagsüber (wenn niemand zuhause ist) automatisch abzusenken. Eine Nachtabsenkung von 4–5 °C spart 10–15 % Heizenergie.","Setzen Sie Zeitprogramme so, dass die Heizung 30–60 Minuten vor Ihrer Anwesenheit wieder anläuft. So ist es warm wenn Sie nach Hause kommen, ohne die ganze Zeit auf Vollgas zu heizen."]},{"heading":"Heizung entlüften","paragraphs":["Luft in den Heizkörpern ist ein häufiges und unterschätztes Problem. Wenn Heizkörper oben kalt bleiben oder gluckernde Geräusche machen, ist Luft eingeschlossen. Die Heizung muss dann mehr Energie aufwenden, um die gleiche Wärme zu liefern.","Entlüften ist einfach: Lüftungsventil am Heizkörper aufdrehen bis Wasser austritt — fertig. Am besten jährlich zu Heizsaisonbeginn."]},{"heading":"Tarifwechsel — der größte Hebel","paragraphs":["Alle technischen Maßnahmen zusammen sparen selten mehr als 20 %. Ein Anbieterwechsel kann allein 15–30 % der Gasrechnung einsparen — ohne jede Investition.","EnergieClever vergleicht über 100 Gasanbieter und findet den günstigsten Tarif für Ihren Verbrauch und Ihren Standort. Der Wechsel dauert 5 Minuten, wir kündigen Ihren alten Vertrag und übernehmen alles."]}]'::jsonb,
  6, true, '2026-04-15 00:00:00+00'
),
(
  'ein-vertrag-statt-zwei',
  'Ein Vertrag statt zwei: So einfach geht der Strom-Gas-Wechsel',
  'Strom und Gas bei einem Anbieter — das spart Zeit, Bürokratie und oft auch Geld. Wir erklären wie.',
  'https://images.unsplash.com/photo-1548502032-4d0e6d99b31e?w=1200&h=630&fit=crop&q=80',
  'Strom & Gas',
  'EnergieClever Redaktion',
  '[{"heading":"Was ist ein Kombi-Tarif?","paragraphs":["Ein Kombi-Tarif fasst Strom- und Gasversorgung in einem einzigen Vertrag zusammen. Statt zwei Rechnungen, zwei Kundennummern und zwei Ansprechpartnern gibt es nur noch einen Anbieter für beide Sparten.","Wirtschaftlich interessant wird es durch den Doppelbonus: Viele Anbieter zahlen 100–300 € extra, wenn Strom und Gas gleichzeitig gewechselt werden."]},{"heading":"Wie viel kann man sparen?","paragraphs":["Beim Tarifvergleich zeigt sich: Kombi-Tarife sind oft 5–15 % günstiger als zwei separate Einzeltarife — selbst ohne Doppelbonus. Das liegt an Mengenrabatten, die Anbieter bei gebündelten Kunden weitergeben.","Für einen Musterhaushalt mit 3.500 kWh Strom und 15.000 kWh Gas ergibt das eine typische Jahresersparnis von 200–450 € gegenüber Grundversorgertarifen."]},{"heading":"Gibt es Nachteile?","paragraphs":["Der wichtigste Nachteil: Sie sind bei einem einzigen Anbieter. Läuft der Service nicht gut, betrifft das beide Sparten. Deshalb: Prüfen Sie Bewertungen und Kundenzufriedenheit des Anbieters.","Ein weiterer Punkt: Läuft der Strom-Vertrag aus und der Gas-Vertrag noch nicht, müssen Sie entweder beide gleichzeitig verlängern oder neu verhandeln — das kann unflexibel sein."]},{"heading":"Schritt für Schritt zum Kombi-Tarif","paragraphs":["1. Jahresverbrauch beider Sparten heraussuchen (Jahresabrechnung). 2. Über EnergieClever vergleichen — wir zeigen Kombi-Angebote und Einzeltarife im direkten Vergleich. 3. Online abschließen, wir kündigen beide alten Verträge und koordinieren die Übergabe."]}]'::jsonb,
  5, true, '2026-03-28 00:00:00+00'
),
(
  'solaranlage-installation',
  'Solaranlage installieren: Schritt für Schritt erklärt',
  'Von der Planung bis zur Einspeisung — so läuft die Installation einer Solaranlage in Deutschland ab.',
  'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&h=630&fit=crop&q=80',
  'Solar',
  'EnergieClever Redaktion',
  '[{"heading":"Schritt 1: Dachanalyse und Planung","paragraphs":["Bevor ein einziges Modul bestellt wird, steht die gründliche Analyse Ihres Dachs. Ausrichtung (ideal: Süd bis Südwest), Neigung (25–35° optimal), Verschattung durch Bäume oder Nachbarhäuser und die statische Tragfähigkeit müssen geprüft werden.","Moderne Planungstools erlauben eine Simulation der Jahresertrag per Satellitenaufnahme. Gute Installateure bieten das kostenlos an — bestehen Sie darauf."]},{"heading":"Schritt 2: Angebote einholen und vergleichen","paragraphs":["Holen Sie mindestens 3 Angebote ein. Achten Sie dabei nicht nur auf den Gesamtpreis, sondern auf: Modulhersteller und Leistungsgarantie (25 Jahre Standard), Wechselrichtermarke, Installationsqualität und Referenzprojekte.","Vorsicht bei Preisen unter 1.000 € pro kWp — oft werden mindere Komponenten oder schlechte Montagequalität eingesetzt, die langfristig teuer werden."]},{"heading":"Schritt 3: Genehmigungen und Anmeldung","paragraphs":["In den meisten Bundesländern ist eine Solaranlage unter 10 kWp genehmigungsfrei. Trotzdem müssen Sie die Anlage beim Netzbetreiber anmelden und ins Marktstammdatenregister der Bundesnetzagentur eintragen.","Ihr Installateur übernimmt das in der Regel. Fragen Sie explizit danach und lassen Sie sich die Anmeldungsbestätigung aushändigen — ohne diese gibt es keine Einspeisevergütung."]},{"heading":"Schritt 4: Die Montage","paragraphs":["Die eigentliche Montage dauert bei einem Einfamilienhaus 1–3 Tage. Unterkonstruktion, Module, Wechselrichter und DC-Verkabelung werden installiert. Ein optionaler Batteriespeicher wird parallel oder zu einem späteren Zeitpunkt eingebaut.","Während der Montage sollten Sie zuhause sein — nicht um zu helfen, sondern um Fragen zu beantworten und die Qualität im Blick zu behalten."]},{"heading":"Schritt 5: Inbetriebnahme und Einspeisevergütung","paragraphs":["Nach der Montage kommt der Netzbetreiber für den Zählertausch (Smart Meter oder bidirektionaler Zähler). Ab diesem Moment wird eingespeister Strom vergütet: 2026 sind das 8,11 Cent/kWh für Anlagen bis 10 kWp bei Volleinspeisung, 12,88 Cent bei Teileinspeisung.","Die Einspeisevergütung wird für 20 Jahre ab Inbetriebnahme garantiert."]}]'::jsonb,
  8, true, '2026-05-10 00:00:00+00'
),
(
  'solaranlage-foerderungen-2026',
  'Solaranlage: Förderungen & Zuschüsse 2026 im Überblick',
  'KfW, BAFA, Länderförderungen — welche Zuschüsse gibt es 2026 für Solaranlagen? Alle Programme im Überblick.',
  'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1200&h=630&fit=crop&q=80',
  'Solar',
  'EnergieClever Redaktion',
  '[{"heading":"KfW-Programm 270: Erneuerbare Energien","paragraphs":["Das KfW-Programm 270 ist das meistgenutzte Finanzierungsinstrument für Solaranlagen. Es bietet zinsgünstige Kredite mit effektiven Jahreszinsen ab 3,09 % (Stand 06/2026) für Anlagen bis 150 kWp.","Besonders attraktiv: Tilgungszuschüsse von bis zu 20 % sind möglich, wenn die Anlage mit einem Batteriespeicher kombiniert wird. Der Antrag erfolgt über Ihre Hausbank vor Baubeginn."]},{"heading":"BAFA-Förderung für Stromspeicher","paragraphs":["Das BAFA fördert Batteriespeicher, die in Kombination mit einer Solaranlage installiert werden. Der Zuschuss beträgt je nach Bundesland 500–2.000 €, sofern die Anlage unter 30 kWp liegt.","Wichtig: BAFA-Förderung und KfW-Kredit sind kombinierbar. Beantragen Sie zuerst die BAFA-Förderung (vor Auftragsvergabe), dann den KfW-Kredit."]},{"heading":"Landesförderungen: Bayern, NRW und BW","paragraphs":["Bayern: Das Bayerische Solarstromspeicher-Programm fördert Batteriespeicher mit bis zu 1.500 € Zuschuss. Nordrhein-Westfalen: progres.nrw fördert Anlagen bis 30 kWp mit 600 € Festbetrag plus 200 € pro kWh Speicher.","Baden-Württemberg: Wer eine Wallbox für das E-Auto gleichzeitig installiert, erhält einen Kombibonus von bis zu 2.000 €. Alle Programme sind auf den Websites der Landesbehörden abrufbar."]},{"heading":"Einspeisevergütung 2026","paragraphs":["Neben Förderungen erhalten Sie 20 Jahre lang eine gesetzlich garantierte Einspeisevergütung für überschüssigen Solarstrom. 2026 beträgt sie 8,11 Cent/kWh (Anlagen bis 10 kWp, Überschusseinspeisung) — deutlich attraktiver als noch 2024.","Die Vergütung sinkt monatlich leicht (gesetzliche Degression), weshalb eine frühe Inbetriebnahme wirtschaftlich sinnvoll ist."]}]'::jsonb,
  7, true, '2026-05-20 00:00:00+00'
),
(
  'anbieterwechsel-schritt-fuer-schritt',
  'Anbieterwechsel: So einfach läuft es mit EnergieClever',
  'Strom oder Gas wechseln klingt kompliziert — ist es aber nicht. Wir übernehmen alles. So funktioniert''s.',
  'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&h=630&fit=crop&q=80',
  'Service',
  'EnergieClever Redaktion',
  '[{"heading":"Warum überhaupt wechseln?","paragraphs":["Der Energiemarkt ist wettbewerbsintensiv. Wer bisher noch nie gewechselt hat, zahlt mit hoher Wahrscheinlichkeit zu viel. Der Preisunterschied zwischen Grundversorger und einem günstigen Sondertarif beträgt oft 200–500 € pro Jahr — für einen Haushalt mit 3.500 kWh Strom.","Viele Menschen scheuen den Wechsel aus Angst vor Aufwand oder Versorgungslücken. Beides ist unbegründet — der Gesetzgeber schützt Verbraucher, und EnergieClever übernimmt den gesamten Prozess."]},{"heading":"Was EnergieClever für Sie übernimmt","paragraphs":["Nach Ihrem Online-Formular (2 Minuten) kontaktiert Sie ein Berater persönlich. Wir ermitteln den besten Tarif für Ihren Verbrauch und Ihren Wohnort.","Sobald Sie zustimmen: Wir kündigen Ihren alten Vertrag fristgerecht, melden Sie beim neuen Anbieter an und koordinieren den nahtlosen Übergang. Sie müssen keinen einzigen Brief schreiben."]},{"heading":"Wie lange dauert der Wechsel?","paragraphs":["Per Gesetz dauert der Wechselprozess maximal 3 Wochen. Meistens läuft alles schneller. Während der Übergangszeit werden Sie von Ihrem alten Anbieter weiterversorgt — eine Versorgungslücke ist gesetzlich ausgeschlossen.","Ihr neuer Tarif beginnt entweder zum nächstmöglichen Termin (bei fristlosem Wechsel aus dem Grundversorger-Tarif) oder zum Ende Ihrer alten Vertragslaufzeit."]},{"heading":"Was Sie selbst tun müssen","paragraphs":["Genau eine Sache: Das Online-Formular auf EnergieClever ausfüllen (2 Minuten). Jahresverbrauch und PLZ genügen für einen ersten Vergleich. Den Rest erledigen wir.","Optional: Halten Sie Ihre letzte Jahresabrechnung bereit — mit Zählernummer und aktuellem Verbrauch können wir einen noch präziseren Vergleich erstellen."]}]'::jsonb,
  4, true, '2026-02-14 00:00:00+00'
),
(
  'unterlagen-beim-wechsel',
  'Diese Unterlagen brauchst du beim Energieanbieterwechsel',
  'Zählernummer, Ablesewert, Kundennummer — wir erklären welche Daten du für den Wechsel parat haben musst.',
  'https://images.unsplash.com/photo-1568667256549-094345857637?w=1200&h=630&fit=crop&q=80',
  'Service',
  'EnergieClever Redaktion',
  '[{"heading":"Die Zählernummer — wo findet man sie?","paragraphs":["Die Zählernummer ist eine eindeutige Kennzeichnung Ihres Stromzählers und unverzichtbar beim Anbieterwechsel. Sie finden sie direkt auf dem Zähler im Sicherungskasten oder Zählerschrank — meist eine 8–12-stellige Zahl, manchmal mit Buchstaben.","Alternativ steht die Zählernummer auf Ihrer letzten Jahresabrechnung oder auf dem Begrüßungsschreiben Ihres aktuellen Anbieters."]},{"heading":"Der aktuelle Zählerstand","paragraphs":["Der Zählerstand zum Wechselzeitpunkt ist wichtig, damit Ihr alter Anbieter korrekt abrechnet und der neue Anbieter zum richtigen Zeitpunkt beginnt. Lesen Sie ihn kurz vor oder am Tag des Wechsels ab.","Falls Sie vergessen haben, einen Ablesewert zu übermitteln: Kein Problem. Der Netzbetreiber schätzt den Verbrauch anteilig — auf Basis Ihres Jahresverbrauchs. Das ist gesetzlich geregelt und funktioniert zuverlässig."]},{"heading":"Angaben aus der letzten Jahresabrechnung","paragraphs":["Für einen präzisen Vergleich benötigen wir Ihren Jahresverbrauch in kWh — den finden Sie auf der letzten Jahresabrechnung. Außerdem: Ihre Kundennummer beim alten Anbieter (für die Kündigung) und das Vertragsende (damit wir optimal kündigen können).","Ohne Jahresabrechnung kein Problem: Eine Schätzung anhand von Haushaltsgröße oder Wohnfläche reicht für den ersten Vergleich. Genaue Daten verbessern nur das Ergebnis."]},{"heading":"Das war''s schon","paragraphs":["Zählernummer, Jahresverbrauch, PLZ — das sind die drei Kernangaben für einen reibungslosen Wechsel. Alles andere übernimmt EnergieClever.","Füllen Sie unser kurzes Formular aus und ein Berater meldet sich innerhalb von 24 Stunden mit konkreten Angeboten."]}]'::jsonb,
  4, true, '2026-01-30 00:00:00+00'
)
ON CONFLICT (slug) DO NOTHING;
